import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./reset.css";
import "./globals.css";
import Topbar from "@/component/UserLayout/Topbar";
import { Orbitron, Poppins } from "next/font/google";
import Footer from "@/component/UserLayout/Footer";

const orbitronSans = Orbitron({
  variable: "--font-orbitron-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PrometexMM",
  description: "Generated by create next app",
  icons: {
    icon: "/img/X.png",
    shortcut: "/img/X.png",
    apple: "/img/X.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${orbitronSans.variable} ${poppins.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Topbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
